/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Question {
  'id' : bigint,
  'topic' : string,
  'explanation' : [] | [string],
  'year' : string,
  'answerOptions' : Array<string>,
  'questionText' : string,
  'correctAnswerIndex' : bigint,
}
export interface SubscriptionSettings {
  'yearlyPrice' : bigint,
  'monthlyPrice' : bigint,
  'freeTrialDays' : bigint,
}
export interface UserProfile {
  'age' : bigint,
  'name' : string,
  'gender' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addQuestion' : ActorMethod<[Question], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAdminQuestions' : ActorMethod<[], Array<Question>>,
  'getByTopic' : ActorMethod<[string], Array<Question>>,
  'getByYear' : ActorMethod<[string], Array<Question>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getQuestions' : ActorMethod<[], Array<Question>>,
  'getSubscriptionSettings' : ActorMethod<[], SubscriptionSettings>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordAttempt' : ActorMethod<[bigint, bigint], boolean>,
  'removeQuestion' : ActorMethod<[bigint], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateSubscriptionSettings' : ActorMethod<[SubscriptionSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];