/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Question = IDL.Record({
  'id' : IDL.Nat,
  'topic' : IDL.Text,
  'explanation' : IDL.Opt(IDL.Text),
  'year' : IDL.Text,
  'answerOptions' : IDL.Vec(IDL.Text),
  'questionText' : IDL.Text,
  'correctAnswerIndex' : IDL.Nat,
});
export const BillingCycle = IDL.Variant({
  'monthly' : IDL.Null,
  'yearly' : IDL.Null,
});
export const SubscriptionPlan = IDL.Record({
  'id' : IDL.Nat,
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'billingCycle' : BillingCycle,
  'price' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addQuestion' : IDL.Func([Question], [IDL.Bool], []),
  'addSubscriptionPlan' : IDL.Func([SubscriptionPlan], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAdminQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getByTopic' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
  'getByYear' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getSubscriptionPlans' : IDL.Func([], [IDL.Vec(SubscriptionPlan)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordAttempt' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'removeQuestion' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'topic' : IDL.Text,
    'explanation' : IDL.Opt(IDL.Text),
    'year' : IDL.Text,
    'answerOptions' : IDL.Vec(IDL.Text),
    'questionText' : IDL.Text,
    'correctAnswerIndex' : IDL.Nat,
  });
  const BillingCycle = IDL.Variant({
    'monthly' : IDL.Null,
    'yearly' : IDL.Null,
  });
  const SubscriptionPlan = IDL.Record({
    'id' : IDL.Nat,
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'billingCycle' : BillingCycle,
    'price' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addQuestion' : IDL.Func([Question], [IDL.Bool], []),
    'addSubscriptionPlan' : IDL.Func([SubscriptionPlan], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAdminQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getByTopic' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
    'getByYear' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getSubscriptionPlans' : IDL.Func(
        [],
        [IDL.Vec(SubscriptionPlan)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordAttempt' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'removeQuestion' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };