/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PaymentRecord {
  'id' : string,
  'status' : PaymentStatus,
  'userName' : string,
  'paymentMethod' : string,
  'userId' : string,
  'date' : string,
  'approvedAt' : [] | [string],
  'plan' : string,
  'rejectedAt' : [] | [string],
  'deviceId' : [] | [string],
  'utrId' : string,
  'amount' : string,
}
export type PaymentStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Question {
  'id' : bigint,
  'topic' : string,
  'explanation' : [] | [string],
  'year' : string,
  'answerOptions' : Array<string>,
  'questionText' : string,
  'correctAnswerIndex' : bigint,
}
export interface SubscriptionSettings {
  'yearlyPrice' : bigint,
  'monthlyPrice' : bigint,
  'freeTrialDays' : bigint,
}
export interface UserProfile {
  'age' : bigint,
  'name' : string,
  'gender' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSubscription {
  'status' : string,
  'userName' : string,
  'lastLoginDevice' : string,
  'expiryDate' : string,
  'userId' : string,
  'deviceId' : string,
  'paymentRef' : string,
  'planType' : string,
  'startDate' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activateSubscription' : ActorMethod<[UserSubscription], boolean>,
  'addQuestion' : ActorMethod<[Question], boolean>,
  'approvePayment' : ActorMethod<[string, string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelSubscription' : ActorMethod<[string], boolean>,
  'getAdminQuestions' : ActorMethod<[], Array<Question>>,
  'getAllSubscriptions' : ActorMethod<[], Array<UserSubscription>>,
  'getByTopic' : ActorMethod<[string], Array<Question>>,
  'getByYear' : ActorMethod<[string], Array<Question>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPaymentRecords' : ActorMethod<[], Array<PaymentRecord>>,
  'getPaymentRecordsByUser' : ActorMethod<[string], Array<PaymentRecord>>,
  'getQuestions' : ActorMethod<[], Array<Question>>,
  'getSubscriptionByUser' : ActorMethod<[string], [] | [UserSubscription]>,
  'getSubscriptionSettings' : ActorMethod<[], SubscriptionSettings>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordAttempt' : ActorMethod<[bigint, bigint], boolean>,
  'rejectPayment' : ActorMethod<[string, string], boolean>,
  'removeQuestion' : ActorMethod<[bigint], boolean>,
  'resetDeviceBinding' : ActorMethod<[string], boolean>,
  'resetSubscriptionDevice' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitPaymentRecord' : ActorMethod<[PaymentRecord], boolean>,
  'updateLastLoginDevice' : ActorMethod<[string, string], boolean>,
  'updateSubscriptionSettings' : ActorMethod<[SubscriptionSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];