/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserSubscription = IDL.Record({
  'status' : IDL.Text,
  'userName' : IDL.Text,
  'lastLoginDevice' : IDL.Text,
  'expiryDate' : IDL.Text,
  'userId' : IDL.Text,
  'deviceId' : IDL.Text,
  'paymentRef' : IDL.Text,
  'planType' : IDL.Text,
  'startDate' : IDL.Text,
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'topic' : IDL.Text,
  'explanation' : IDL.Opt(IDL.Text),
  'year' : IDL.Text,
  'answerOptions' : IDL.Vec(IDL.Text),
  'questionText' : IDL.Text,
  'correctAnswerIndex' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'gender' : IDL.Text,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PaymentRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : PaymentStatus,
  'userName' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'userId' : IDL.Text,
  'date' : IDL.Text,
  'approvedAt' : IDL.Opt(IDL.Text),
  'plan' : IDL.Text,
  'rejectedAt' : IDL.Opt(IDL.Text),
  'deviceId' : IDL.Opt(IDL.Text),
  'utrId' : IDL.Text,
  'amount' : IDL.Text,
});
export const SubscriptionSettings = IDL.Record({
  'yearlyPrice' : IDL.Nat,
  'monthlyPrice' : IDL.Nat,
  'freeTrialDays' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activateSubscription' : IDL.Func([UserSubscription], [IDL.Bool], []),
  'addQuestion' : IDL.Func([Question], [IDL.Bool], []),
  'approvePayment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelSubscription' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAdminQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getAllSubscriptions' : IDL.Func([], [IDL.Vec(UserSubscription)], ['query']),
  'getByTopic' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
  'getByYear' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPaymentRecords' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'getPaymentRecordsByUser' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PaymentRecord)],
      ['query'],
    ),
  'getQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getSubscriptionByUser' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserSubscription)],
      ['query'],
    ),
  'getSubscriptionSettings' : IDL.Func([], [SubscriptionSettings], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordAttempt' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'rejectPayment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'removeQuestion' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'resetDeviceBinding' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'resetSubscriptionDevice' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitPaymentRecord' : IDL.Func([PaymentRecord], [IDL.Bool], []),
  'updateLastLoginDevice' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateSubscriptionSettings' : IDL.Func([SubscriptionSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserSubscription = IDL.Record({
    'status' : IDL.Text,
    'userName' : IDL.Text,
    'lastLoginDevice' : IDL.Text,
    'expiryDate' : IDL.Text,
    'userId' : IDL.Text,
    'deviceId' : IDL.Text,
    'paymentRef' : IDL.Text,
    'planType' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'topic' : IDL.Text,
    'explanation' : IDL.Opt(IDL.Text),
    'year' : IDL.Text,
    'answerOptions' : IDL.Vec(IDL.Text),
    'questionText' : IDL.Text,
    'correctAnswerIndex' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'gender' : IDL.Text,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PaymentRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : PaymentStatus,
    'userName' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'userId' : IDL.Text,
    'date' : IDL.Text,
    'approvedAt' : IDL.Opt(IDL.Text),
    'plan' : IDL.Text,
    'rejectedAt' : IDL.Opt(IDL.Text),
    'deviceId' : IDL.Opt(IDL.Text),
    'utrId' : IDL.Text,
    'amount' : IDL.Text,
  });
  const SubscriptionSettings = IDL.Record({
    'yearlyPrice' : IDL.Nat,
    'monthlyPrice' : IDL.Nat,
    'freeTrialDays' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activateSubscription' : IDL.Func([UserSubscription], [IDL.Bool], []),
    'addQuestion' : IDL.Func([Question], [IDL.Bool], []),
    'approvePayment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelSubscription' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAdminQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getAllSubscriptions' : IDL.Func(
        [],
        [IDL.Vec(UserSubscription)],
        ['query'],
      ),
    'getByTopic' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
    'getByYear' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPaymentRecords' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'getPaymentRecordsByUser' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PaymentRecord)],
        ['query'],
      ),
    'getQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getSubscriptionByUser' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserSubscription)],
        ['query'],
      ),
    'getSubscriptionSettings' : IDL.Func([], [SubscriptionSettings], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordAttempt' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'rejectPayment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'removeQuestion' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'resetDeviceBinding' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'resetSubscriptionDevice' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitPaymentRecord' : IDL.Func([PaymentRecord], [IDL.Bool], []),
    'updateLastLoginDevice' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateSubscriptionSettings' : IDL.Func([SubscriptionSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };